<h1><?php if(!empty($this->registrations)){$first = $this->registrations[0]; echo $first->getGame()->getName();} ?></h1>
<table>
    <?php
    if(isset($this->registrationError))
        echo $this->registrationError;
    if(isset($this->registrationMess))
        echo $this->registrationMess;
    $nbPlayers = 0;
    if(Zend_Auth::getInstance()->hasIdentity()){
    $identity = Zend_Auth::getInstance()->getIdentity();
    $identifie = App_Facade_Lecture::getInstance()->getUserById($identity->id);
    if(!empty($this->registrations)){
        foreach ($this->registrations as $reg) {
            $nbPlayers++;
            foreach($this->accountList($identifie) as $account){
                if($account->getName() == $reg->getAccount()->getName()){
                    $desinscription = '<a href="'.$this->baseUrl().$this->url(array('controller' => 'index', 'action' => 'desinscription', 'reg' => $reg->getId()), 'default', true).'">
                                        <img src="'.$this->baseUrl().'/images/delete.png" alt="desinscription"/></a>';
                    break;
                }
                else
                    $desinscription = '';
            }
            echo '<tr><td>'.$reg->getAccount()->getName().'</td><td>'.$reg->getAccount()->getElo().'</td><td>'.$desinscription.'</td></tr>';
        }
    }
    for($i = $nbPlayers; $i < 11; $i++)
        echo '<tr><td>'.$this->form.'</td></tr>';
    }
    ?>
</table>