<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <?php
        $identity = Zend_Auth::getInstance()->getIdentity();
        echo $this->headTitle();
        echo $this->headLink()->appendStylesheet('/css/style.css');
        echo $this->headScript()->appendFile('http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js')
                                ->appendFile('/js/hon.js');
    ?>
    </head>
    <body>
        <div id="align">
            <div id="header">
                <div id="connexion">
                    <div id="loginBox">
                        <?php
                        if( Zend_Auth::getInstance()->hasIdentity()){
                            echo $this->loggedInAs();
                            $identifie = App_Facade_Lecture::getInstance()->getUserById($identity->id);
                        }
                        else
                            echo $this->loginForm($this->loginForm);
                        
                        ?>
                    </div>
                    <div id="accountChoice">
                        <select id="accountSelect">
                            <?php
                            $accounts = $this->accountList($identifie);
                            foreach ($accounts as $account) {
                                echo '<option value="'.$account->getId().'">'.$account->getName().'</option>';
                            }
                            ?>
                        </select>
                    </div>
                </div>
                <?php if( !Zend_Auth::getInstance()->hasIdentity()){ ?>
                <div id="mdp">
                    <a href="<?php echo $this->baseUrl().$this->url(array('controller' => 'auth', 'action' => 'pass'), 'default', true); ?>" >Mot de passe oublié?</a>
                    <a href="<?php echo $this->baseUrl().$this->url(array('controller' => 'auth', 'action' => 'inscription'), 'default', true); ?>" >Inscription</a>
                </div>
                <?php }?>
            </div>
            <div>
                <ul>
                    <li><a href="<?php echo $this->baseUrl().$this->url(array('controller' => 'news', 'action' => 'index'), 'default', true); ?>">News</a></li>
                    <li><a href="<?php echo $this->baseUrl().$this->url(array('controller' => 'gameList', 'action' => 'index'), 'default', true); ?>">Matchs</a></li>
                    <li><a href="<?php echo $this->baseUrl().$this->url(array('controller' => 'ladder', 'action' => 'index'), 'default', true); ?>">Ladder</a></li>
                </ul>
            </div>
            <div id="content">
                <?php echo $this->layout()->content; ?>
            </div>
        </div>
    </body>
</html>