<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <?php
        $identity = Zend_Auth::getInstance()->getIdentity();
        echo $this->headTitle();
        echo $this->headLink()->appendStylesheet('/css/style.css');
        echo $this->headScript()->appendFile('http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js')
                                ->appendFile('/js/hon.js');
    ?>
    </head>
    <body>
        <div id="align">
		
		  <div id="header-fix">
			
				<div id="header">
                <div id="connexion">
                    <div id="loginBox">
                        <?php
                        if( Zend_Auth::getInstance()->hasIdentity()){
                            echo $this->loggedInAs();
                            $identifie = App_Facade_Lecture::getInstance()->getUserById($identity->id);
                        }
                        else
                            echo $this->loginForm($this->loginForm);
                        
                        ?>
                    </div>
					<?php
					if( Zend_Auth::getInstance()->hasIdentity()){ ?>
                    <div id="accountChoice">
                        Connecté en tant que :
                        <select id="accountSelect">
                            <?php
							
                            $accounts = $this->accountList($identifie);
							
                            foreach ($accounts as $account) {
                                
                                if(Zend_Registry::get('Session')->account == $account->getId())
                                    echo '<option selected="selected" value="'.$account->getId().'">'.$account->getName().'</option>';
                                else
                                    echo '<option value="'.$account->getId().'">'.$account->getName().'</option>';
                            }
							?>
                        </select>
                    </div>
					<?php }?>
                </div>
                <?php if( !Zend_Auth::getInstance()->hasIdentity()){ ?>
                <div id="mdp">
                    <a href="<?php echo $this->baseUrl().$this->url(array('controller' => 'auth', 'action' => 'pass'), 'default', true); ?>" >Mot de passe oublié?</a>
                    <a href="<?php echo $this->baseUrl().$this->url(array('controller' => 'auth', 'action' => 'inscription'), 'default', true); ?>" >Inscription</a>
                </div>
                <?php }?>
            </div>
			
		  </div>
		  
		  <div id="global-top">
			
				<div id="left-bub">
				
				</div>
				
				<div id="mid-global-top">
				
					<h1>Hon Bourbax-league, IH Heroes of newerst France</h1>
				
				</div>
				
				
				<div id="right-bub">
				</div>
				
				<div class="clear"></div>
		  </div>
		  
		  <div id="global">
			
			<div id="bubbles"></div>
			
			<div id="content">
			
				<div id="content-top">
				
					<h3>BOURBAX LEAGUE</h3>
				
				</div>
			
				<div id="content-mid">
					
					<div id="menu">
					<div>
							<ul class="menu">
								<li><a href="<?php echo $this->baseUrl().$this->url(array('controller' => 'news', 'action' => 'index'), 'default', true); ?>"><img alt="" title="news" src="images/texte/news.png" /></a></li>
								<li><a href="<?php echo $this->baseUrl().$this->url(array('controller' => 'gameList', 'action' => 'index'), 'default', true); ?>"><img alt="" title="fiche de match" src="images/texte/fiche-de-match.png" /></a></li>
								<li><a href="<?php echo $this->baseUrl().$this->url(array('controller' => 'ladder', 'action' => 'index'), 'default', true); ?>"><img alt="" title="ladder" src="images/texte/ladder.png" /></a></li>
							</ul>
					  </div>
					</div>
				
					<div id="text">
					
					  
					  <div id="content">
							<?php echo $this->layout()->content; ?>
					  </div>
					  
					</div>  
					  
			  </div>
		  
			  <div id="content-bot">
			  </div>
			  
		   </div>
		  
			<div id="balpha"></div>
		  
		 </div> 
		  
        </div>
    </body>
</html>