<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <?php
        echo $this->headTitle();
        echo $this->headLink()->appendStylesheet('/css/style.css');
        echo $this->headScript()->appendFile('http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js');
    ?>
    </head>
    <body>
        <div id="align">
            <div id="header">
                <div id="connexion">
                    <div id="loginBox">
                        <?php
                        /*if( Zend_Auth::getInstance()->hasIdentity()){
                            echo $this->loggedInAs();
                            //$identifie = App_Facade_Lecture::getInstance()->getAgent($identity->id);
                        }
                        else
                            echo $this->loginForm($this->loginForm);*/
                        ?>
                    </div>
                </div>
                <?php if( !Zend_Auth::getInstance()->hasIdentity()){ ?>
                <div id="mdp">
                    <a href="<?php echo $this->baseUrl().$this->url(array('controller' => 'auth', 'action' => 'pass'), 'default', true); ?>" >Mot de passe oublié?</a>
                    <a href="<?php echo $this->baseUrl().$this->url(array('controller' => 'auth', 'action' => 'inscription'), 'default', true); ?>" >Inscription</a>
                </div>
                <?php }?>
            </div>
            <div id="menu">
                <ul>
                </ul>
            </div>
            <div id="content">
                <?php echo $this->layout()->content; ?>
            </div>
        </div>
    </body>
</html>